TARGET    = BH_launcher.x
OBJECT_01 = BH_launcher.o
SOURCE_01 = BH_launcher.c

$(TARGET): $(OBJECT_01)
	gcc -g -o $(TARGET) $(OBJECT_01) -lm -std=c99

$(OBJECT_01) : $(SOURCE_01)
	gcc -g -c $(SOURCE_01) -o $(OBJECT_01)

all : $(TARGET)

clean :
	-rm $(TARGET) $(OBJS)